name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          TARGET_REPO: Nick-QI/nick-qi.github.io
          TARGET_BRANCH: master
          BUILD_SCRIPT: yarn && yarn build && echo "exp.chenqi.fun" > docs/.vuepress/dist/CNAME
          BUILD_DIR: docs/.vuepress/dist/